/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-PDFio.h
 #	source generated by 4D Plugin Wizard
 #	Project : PDFio
 #	author : miyako
 #	2023/05/15
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_PDFIO_H
#define PLUGIN_PDFIO_H

#include "4DPluginAPI.h"
#include "pdfio.h"
#include "C_TEXT.h"
#include "4DPlugin-JSON.h"

#include <time.h>

#pragma mark -

static void PDFio_Get_metadata(PA_PluginParameters params);

#endif /* PLUGIN_PDFIO_H */
